### PR TITLE
feat: lighter-image-files (draft)

### PR DESCRIPTION
**Pull request by martinabab**
#### Pull Request purpose

[ ] Documentation update
[ ] Bug fix
[X] New rule
[ ] Updates an existing rule
[ ] Add something to the core
[ ] Other, please explain:

#### Checklist

[ ] Update CHANGELOG.md
[ ] Update task status in release plan (README)
[ ] Docs added (/docs/rules/<rule_name>)
[ ] Docs ready to be added to website (ec0lint.com)

### CODE REVIEW

**Comment by malwinq** [comment]
Please fix the checks:

Run node Makefile checkRuleFiles
Validating rules
Missing setting for lighter-image-files in tools/rule-types.json
Missing rule from index (./lib/rules/index.js): lighter-image-files. If you just added a new rule then add an entry for it in this file.
Missing tests for rule lighter-image-files

**Review by malwinq — COMMENTED** [review]
changes look very good overall, very clean code! one thing from me - please add some positive tests too, i.e. returning no message when the image is fine

**Review by nemmip — APPROVED** [review]
lgtm

**Comment by malwinq** [comment]
perfect, thanks!

**Pull request merged**
